spring:

  main:
    allow-bean-definition-overriding: true

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    default-property-inclusion: non_empty

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  r2dbc:
    initialization-mode: always
    url: r2dbc:h2:file:///./h2db/tododb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    hikari:
      connection-timeout: 500
      idle-timeout: 3000

  output:
    ansi:
      enabled: ALWAYS

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

logging:
  level:
    org.springframework.http: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.data: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari.Hikari: DEBUG
    com.ryunen344.miyoshi.demo: DEBUG

debug: true